export const DEFAULT_COMPANY_PRESETS = {
  dgrPackaging: {
    companyName: 'DGR PACKAGING COMPANY',
    companyAddress: 'SHOP NO.2, OPP. BLUE DART, NEAR, SAHAR CARGO COMPLEX, ANDHERI (E)',
    companyCityPin: 'MUMBAI - 400 099',
    companyPan: 'CBKPK7600K',
    companyGstin: '27CBKPK7600K1ZE',
    companyTel: '022 - 26828108',
    companyEmail: 'dgrpackaging@gmail.com',
    bankName: 'HDFC BANK LTD',
    accountNumber: '06687630000070',
    ifscCode: 'HDFC0003126',
    swiftCode: 'HDFCINBBXXX',
    branchName: 'MAHAD-4',
  },
  dgrGlobalLogistics: {
    companyName: 'DGR GLOBAL LOGISTICS',
    companyAddress: 'GROUND FLOOR, ROOM-003, NX TOWER GM NAGAR, NARANGI BAYPASS ROAD, VIRAR EAST',
    companyCityPin: '401305-PALGHAR, MAHARASHTRA, INDIA',
    companyPan: 'CBKPK7600K',
    companyGstin: '27NSAPK0224B1Z7',
    companyTel: '+91 9326392294',
    companyEmail: 'dgr.export.logistics@gmail.com',
    bankName: 'HDFC BANK LTD',
    accountNumber: '5020 0112 5568 92',
    ifscCode: 'HDFC0000994',
    swiftCode: 'HDFCINBBXXX',
    branchName: 'VIRAR EAST - STATION ROAD',
  },
};

export const taxInvoiceSchema = {
  code: 'TAX_INVOICE',
  name: 'Tax Invoice / Billing',
  category: 'OTHER',
  hasPackages: false,
  sections: [
    {
      id: 'invoiceDetails',
      title: 'Invoice Details',
      fields: [
        { name: 'invoiceNumber', label: 'Invoice Number', type: 'text', width: 'third', required: true, placeholder: 'e.g. DGR/0466/26-27' },
        { name: 'invoiceDate', label: 'Invoice Date', type: 'text', width: 'third', required: true, placeholder: 'DD-MM-YYYY' },
        { name: 'placeOfSupply', label: 'Place of Supply', type: 'text', width: 'third', placeholder: 'Maharashtra (27)' },
        { name: 'reverseCharge', label: 'Reverse Charge', type: 'select', width: 'third', options: [{ value: 'N', label: 'No (N)' }, { value: 'Y', label: 'Yes (Y)' }] },
        { name: 'transport', label: 'Transport / Mode', type: 'text', width: 'third', placeholder: 'BY ROAD / AIR' },
        { name: 'ewayBillNo', label: 'E-Way Bill No.', type: 'text', width: 'third' },
        { name: 'airwayBillNo', label: 'Airway Bill No (AWB)', type: 'text', width: 'third', placeholder: 'e.g. 176-6268 0251' },
        { name: 'poNumberAndDate', label: 'P.O. No. & Date', type: 'text', width: 'third' },
        { name: 'noOfPackages', label: 'No. of Packages', type: 'text', width: 'third', placeholder: 'e.g. 02 PKGS' },
        { name: 'grossWeight', label: 'Gross Weight', type: 'text', width: 'third', placeholder: 'e.g. 50.00 KG' },
        { name: 'transportName', label: 'Transport Name', type: 'text', width: 'third' },
        { name: 'paidToPaid', label: 'Paid / To-Paid', type: 'text', width: 'third' },
        { name: 'referenceName', label: 'Reference Name', type: 'text', width: 'third' },
        { name: 'contactNumber', label: 'Contact Number', type: 'text', width: 'third' },
      ],
    },
    {
      id: 'companyDetails',
      title: 'Issuer / Company Details',
      fields: [
        { name: 'companyName', label: 'Company Name', type: 'text', width: 'half', required: true },
        { name: 'companyGstin', label: 'GSTIN', type: 'text', width: 'half', required: true },
        { name: 'companyPan', label: 'PAN', type: 'text', width: 'half' },
        { name: 'companyTel', label: 'Phone', type: 'text', width: 'half' },
        { name: 'companyEmail', label: 'Email', type: 'text', width: 'half' },
        { name: 'companyCityPin', label: 'City & Pin', type: 'text', width: 'half' },
        { name: 'companyAddress', label: 'Full Address', type: 'textarea', width: 'full' },
      ],
    },
    {
      id: 'buyerDetails',
      title: 'Billed To (Buyer)',
      fields: [
        { name: 'buyerName', label: 'Buyer Name / Company', type: 'text', width: 'full', required: true },
        { name: 'buyerAddress', label: 'Buyer Address', type: 'textarea', width: 'full' },
        { name: 'buyerState', label: 'State', type: 'text', width: 'half', placeholder: 'Maharashtra (27)' },
        { name: 'buyerGstin', label: 'GSTIN / UIN', type: 'text', width: 'half' },
      ],
    },
    {
      id: 'consigneeDetails',
      title: 'Shipped To (Delivery)',
      fields: [
        { name: 'consigneeName', label: 'Consignee / Delivery Name', type: 'text', width: 'full' },
        { name: 'consigneeAddress', label: 'Delivery Address', type: 'textarea', width: 'full' },
        { name: 'consigneeState', label: 'State', type: 'text', width: 'half', placeholder: 'Maharashtra (27)' },
        { name: 'consigneeGstin', label: 'GSTIN / UIN', type: 'text', width: 'half' },
      ],
    },
    {
      id: 'bankDetails',
      title: 'Bank & Payment Details',
      fields: [
        { name: 'bankName', label: 'Bank Name', type: 'text', width: 'half' },
        { name: 'accountNumber', label: 'Account Number', type: 'text', width: 'half' },
        { name: 'ifscCode', label: 'RTGS / NEFT IFSC', type: 'text', width: 'third' },
        { name: 'swiftCode', label: 'Swift Code', type: 'text', width: 'third' },
        { name: 'branchName', label: 'Branch', type: 'text', width: 'third' },
      ],
    },
  ],
};
